sep: ";"

target: pcr
features:
  - age
  - erihc
  - prihc
  - her2
  - tstage
  - nodalstatus
  - grade

categorical_features:
  - erihc
  - prihc
  - her2

features_range: 
  name: "age"
  min: 0
  max: 120
